// Mocks generated by Mockito 5.0.17 from annotations
// in headline_news/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:convert' as _i15;
import 'dart:typed_data' as _i16;

import 'package:dartz/dartz.dart' as _i2;
import 'package:headline_news/common/failure.dart' as _i6;
import 'package:headline_news/common/network_info.dart' as _i12;
import 'package:headline_news/data/datasources/article_local_data_source.dart'
    as _i10;
import 'package:headline_news/data/datasources/article_remote_data_source.dart'
    as _i8;
import 'package:headline_news/data/datasources/db/database_helper.dart' as _i13;
import 'package:headline_news/data/models/article_model.dart' as _i9;
import 'package:headline_news/data/models/article_table.dart' as _i11;
import 'package:headline_news/domain/entities/article.dart' as _i7;
import 'package:headline_news/domain/repositories/article_repository.dart'
    as _i4;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i14;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeResponse_1 extends _i1.Fake implements _i3.Response {}

class _FakeStreamedResponse_2 extends _i1.Fake implements _i3.StreamedResponse {
}

/// A class which mocks [ArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepository extends _i1.Mock implements _i4.ArticleRepository {
  MockArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>
      getTopHeadlineArticles() => (super.noSuchMethod(
          Invocation.method(#getTopHeadlineArticles, []),
          returnValue: Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>
      getHeadlineBusinessArticles() => (super.noSuchMethod(
          Invocation.method(#getHeadlineBusinessArticles, []),
          returnValue: Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>> getArticleCategory(
          String? category) =>
      (super.noSuchMethod(Invocation.method(#getArticleCategory, [category]),
          returnValue: Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>> searchArticles(
          String? query,
          {int? page = 1}) =>
      (super.noSuchMethod(
          Invocation.method(#searchArticles, [query], {#page: page}),
          returnValue: Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> saveBookmarkArticle(
          _i7.Article? article) =>
      (super.noSuchMethod(Invocation.method(#saveBookmarkArticle, [article]),
              returnValue: Future<_i2.Either<_i6.Failure, String>>.value(
                  _FakeEither_0<_i6.Failure, String>()))
          as _i5.Future<_i2.Either<_i6.Failure, String>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> removeBookmarkArticle(
          _i7.Article? article) =>
      (super.noSuchMethod(Invocation.method(#removeBookmarkArticle, [article]),
              returnValue: Future<_i2.Either<_i6.Failure, String>>.value(
                  _FakeEither_0<_i6.Failure, String>()))
          as _i5.Future<_i2.Either<_i6.Failure, String>>);
  @override
  _i5.Future<bool> isAddedToBookmarkArticle(String? url) =>
      (super.noSuchMethod(Invocation.method(#isAddedToBookmarkArticle, [url]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>
      getBookmarkArticles() => (super.noSuchMethod(
          Invocation.method(#getBookmarkArticles, []),
          returnValue: Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
}

/// A class which mocks [ArticleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRemoteDataSource extends _i1.Mock
    implements _i8.ArticleRemoteDataSource {
  MockArticleRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.ArticleModel>> getTopHeadlineArticles() =>
      (super.noSuchMethod(Invocation.method(#getTopHeadlineArticles, []),
              returnValue:
                  Future<List<_i9.ArticleModel>>.value(<_i9.ArticleModel>[]))
          as _i5.Future<List<_i9.ArticleModel>>);
  @override
  _i5.Future<List<_i9.ArticleModel>> getHeadlineBusinessArticles() =>
      (super.noSuchMethod(Invocation.method(#getHeadlineBusinessArticles, []),
              returnValue:
                  Future<List<_i9.ArticleModel>>.value(<_i9.ArticleModel>[]))
          as _i5.Future<List<_i9.ArticleModel>>);
  @override
  _i5.Future<List<_i9.ArticleModel>> getArticleCategory(String? category) =>
      (super.noSuchMethod(Invocation.method(#getArticleCategory, [category]),
              returnValue:
                  Future<List<_i9.ArticleModel>>.value(<_i9.ArticleModel>[]))
          as _i5.Future<List<_i9.ArticleModel>>);
  @override
  _i5.Future<List<_i9.ArticleModel>> searchArticles(String? query, int? page) =>
      (super.noSuchMethod(Invocation.method(#searchArticles, [query, page]),
              returnValue:
                  Future<List<_i9.ArticleModel>>.value(<_i9.ArticleModel>[]))
          as _i5.Future<List<_i9.ArticleModel>>);
}

/// A class which mocks [ArticleLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleLocalDataSource extends _i1.Mock
    implements _i10.ArticleLocalDataSource {
  MockArticleLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertBookmarkArticle(_i11.ArticleTable? article) =>
      (super.noSuchMethod(Invocation.method(#insertBookmarkArticle, [article]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> removeBookmarkArticle(_i11.ArticleTable? article) =>
      (super.noSuchMethod(Invocation.method(#removeBookmarkArticle, [article]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i11.ArticleTable?> getArticleByUrl(String? url) =>
      (super.noSuchMethod(Invocation.method(#getArticleByUrl, [url]),
              returnValue: Future<_i11.ArticleTable?>.value())
          as _i5.Future<_i11.ArticleTable?>);
  @override
  _i5.Future<List<_i11.ArticleTable>> getBookmarkArticles() =>
      (super.noSuchMethod(Invocation.method(#getBookmarkArticles, []),
              returnValue:
                  Future<List<_i11.ArticleTable>>.value(<_i11.ArticleTable>[]))
          as _i5.Future<List<_i11.ArticleTable>>);
  @override
  _i5.Future<void> cacheTopHeadlineArticles(
          List<_i11.ArticleTable>? articles) =>
      (super.noSuchMethod(
          Invocation.method(#cacheTopHeadlineArticles, [articles]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<_i11.ArticleTable>> getCachedTopHeadlineArticles() =>
      (super.noSuchMethod(Invocation.method(#getCachedTopHeadlineArticles, []),
              returnValue:
                  Future<List<_i11.ArticleTable>>.value(<_i11.ArticleTable>[]))
          as _i5.Future<List<_i11.ArticleTable>>);
  @override
  _i5.Future<void> cacheHeadlineBusinessArticles(
          List<_i11.ArticleTable>? articles) =>
      (super.noSuchMethod(
          Invocation.method(#cacheHeadlineBusinessArticles, [articles]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<_i11.ArticleTable>> getCachedHeadlineBusinessArticles() =>
      (super.noSuchMethod(
              Invocation.method(#getCachedHeadlineBusinessArticles, []),
              returnValue:
                  Future<List<_i11.ArticleTable>>.value(<_i11.ArticleTable>[]))
          as _i5.Future<List<_i11.ArticleTable>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i12.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i13.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i14.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i14.Database?>.value())
          as _i5.Future<_i14.Database?>);
  @override
  _i5.Future<void> insertCacheTransactionArticles(
          List<_i11.ArticleTable>? articles, String? category) =>
      (super.noSuchMethod(
          Invocation.method(
              #insertCacheTransactionArticles, [articles, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getCacheArticles(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheArticles, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
  @override
  _i5.Future<int> clearCacheArticles(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearCacheArticles, [category]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> insertBookmarkArticle(_i11.ArticleTable? article) =>
      (super.noSuchMethod(Invocation.method(#insertBookmarkArticle, [article]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> removeBookmarkArticle(_i11.ArticleTable? article) =>
      (super.noSuchMethod(Invocation.method(#removeBookmarkArticle, [article]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<Map<String, dynamic>?> getArticleByUrl(String? url) =>
      (super.noSuchMethod(Invocation.method(#getArticleByUrl, [url]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i5.Future<Map<String, dynamic>?>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getBookmarkArticles() =>
      (super.noSuchMethod(Invocation.method(#getBookmarkArticles, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i3.Response>.value(_FakeResponse_1()))
          as _i5.Future<_i3.Response>);
  @override
  _i5.Future<_i3.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i3.Response>.value(_FakeResponse_1()))
          as _i5.Future<_i3.Response>);
  @override
  _i5.Future<_i3.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i15.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i3.Response>.value(_FakeResponse_1()))
          as _i5.Future<_i3.Response>);
  @override
  _i5.Future<_i3.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i15.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i3.Response>.value(_FakeResponse_1()))
          as _i5.Future<_i3.Response>);
  @override
  _i5.Future<_i3.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i15.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i3.Response>.value(_FakeResponse_1()))
          as _i5.Future<_i3.Response>);
  @override
  _i5.Future<_i3.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i15.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i3.Response>.value(_FakeResponse_1()))
          as _i5.Future<_i3.Response>);
  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i16.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i16.Uint8List>.value(_i16.Uint8List(0)))
          as _i5.Future<_i16.Uint8List>);
  @override
  _i5.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_2()))
          as _i5.Future<_i3.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
